services:
  web:
    build: .
    command: flask run --host=0.0.0.0 --port=8000
    volumes:
      - .:/app.py
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    ports:
      - "8000:8000"
